language: php

sudo: false

env:
  global:
    - secure: "GmAUxOyoB4rK1DuHY8MymysZBriNYKqmENRR+K+E3TXmcsMBDUhR6LZqUKfaEWtRM5CRGTYoEgiD6zO2I07eyDcDlTxfaDR/s08lvBcRqNL/+7FkAlPeholyegzHbda+0cfhKJLwEZvSjr/NcZAOltxcBqeBxzJpZmG2qYJJlPaU4wNg0lfjAgWLOSB9+ugEO0vblsIHFpenezzoxzXG6pMFXN/yjwSGyW+1HMmZGy6mu7pWURPPncNTD0DAo4tX9sNUz3jl/Qg/4Jibzd/LBBkEF5thVrco3g1lLIObKkv+kKQP9qLvduVN5NTmUKtcprg1QkzQcO1xRhDcCQv+DTe8RbsJbn17uUMdCvCZpweJohwLKCo2b/3VlQRhemOr0Mmj945EzyZ37XdLB0uzwh1xzo21kmOjxZEO+IhPyhuXKatPinqpKa9VWvTFkaCaNK+URJT2Q+/n8iQJEfx3pLdvyAkBD9iExDn5sWQtizrNOoz/4NoPf0yujhNmrqjQXNPrfJlulUo9Zsr8UKVf4tkh9YQZbhcIAmO2F1G80555a1BahTj2B1I70hvWK6WnkAP4LrBXakquZOt6twlIV5juUdr1WOBXt1hAR03nQ+6wQcoVoLIXRYHU19mQQxU3V5bBlsG8oPzEVEcSbQvqzGYOfjgMk1N1iS39kKuamK0="

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

stages:
  - style
  - test

jobs:
  include:
    - stage: Style

      php: 7.0

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - composer install

      before_script:
        - mkdir -p $HOME/.php-cs-fixer

      script:
        - vendor/bin/php-cs-fixer fix --config=.php_cs --diff --dry-run --verbose

    - &TEST

      stage: Test

      php: 7.0

      env: WITH_LOWEST=true

      before_install:
        - source .travis/xdebug.sh
        - xdebug-disable
        - composer validate
        - if [[ -n "$GITHUB_TOKEN" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi

      install:
        - if [[ "$WITH_LOWEST" == "true" ]]; then composer update --prefer-lowest; fi
        - if [[ "$WITH_LOCKED" == "true" ]]; then composer install; fi
        - if [[ "$WITH_HIGHEST" == "true" ]]; then composer update; fi

      script:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-enable; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then vendor/bin/phpunit --configuration=test/Unit/phpunit.xml --coverage-clover=build/logs/clover.xml; else vendor/bin/phpunit --configuration=test/Unit/phpunit.xml; fi
        - if [[ "$WITH_COVERAGE" == "true" ]]; then xdebug-disable; fi
        - vendor/bin/phpunit --configuration=test/Integration/phpunit.xml

      after_success:
        - if [[ "$WITH_COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash); fi

    - <<: *TEST

      php: 7.0

      env: WITH_LOCKED=true

    - <<: *TEST

      php: 7.0

      env: WITH_HIGHEST=true

    - <<: *TEST

      php: 7.1

      env: WITH_LOWEST=true

    - <<: *TEST

      php: 7.1

      env: WITH_LOCKED=true WITH_COVERAGE=true

    - <<: *TEST

      php: 7.1

      env: WITH_HIGHEST=true

    - <<: *TEST

      php: 7.2

      env: WITH_LOWEST=true

    - <<: *TEST

      php: 7.2

      env: WITH_LOCKED=true

    - <<: *TEST

      php: 7.2

      env: WITH_HIGHEST=true

notifications:
  email: false
